import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8fafc' },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 50,
        paddingBottom: 20,
        paddingHorizontal: 16,
        backgroundColor: '#ffffff',
        elevation: 2,
    },
    botaoVoltar: { flexDirection: 'row', alignItems: 'center' },
    textoVoltar: { color: '#475569', fontWeight: 'bold', marginLeft: 4 },
    titulo: { fontSize: 18, fontWeight: 'bold', color: '#1e293b' },
    content: { padding: 16 },
    cardForm: {
        backgroundColor: '#ffffff',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        marginBottom: 20,
    },
    label: { fontSize: 13, fontWeight: '700', color: '#64748b', marginBottom: 6 },
    input: {
        backgroundColor: '#f8fafc',
        borderRadius: 8,
        padding: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#cbd5e1',
    },
    pickerContainer: {
        backgroundColor: '#f8fafc',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#cbd5e1',
        marginBottom: 20,
    },
    botaoSalvar: {
        backgroundColor: '#475569',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    textoBotaoSalvar: { color: '#ffffff', fontWeight: 'bold' },
    subtitulo: { fontSize: 16, fontWeight: 'bold', color: '#1e293b', marginBottom: 12 },
    itemUsuario: {
        backgroundColor: '#ffffff',
        padding: 12,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    avatarCirculo: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#94a3b8',
        justifyContent: 'center',
        alignItems: 'center',
    },
    nomeUser: { fontSize: 15, fontWeight: 'bold', color: '#334155' },
    loginUser: { fontSize: 12, color: '#94a3b8', textTransform: 'capitalize' },
});