import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f4f8', 
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 30,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2c2c2e',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titulo: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#020202', 
    textTransform: 'uppercase',
    letterSpacing: 2,
    maxWidth: '50%',
  },
  botaoVoltar: {
    paddingVertical: 8,
    paddingRight: 12,
    justifyContent: 'center',
  },
  textoVoltar: {
    color: '#0284c7', // Azul padrão Maria Auxiliadora
    fontSize: 14,
    fontWeight: 'bold',
  },

  cardPaciente: {
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderLeftWidth: 4,
    borderLeftColor: '#0284c7',
    elevation: 2,
  },
  nomePaciente: { fontSize: 16, fontWeight: 'bold', color: '#1e293b' },
  subtituloPaciente: { fontSize: 14, color: '#64748b' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalTitulo: { fontSize: 20, fontWeight: 'bold', color: '#1e293b' },
  label: { fontSize: 14, fontWeight: 'bold', color: '#475569', marginTop: 10, marginBottom: 4 },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#f8fafc',
  },
  secaoHistorico: {
    marginTop: 20,
    padding: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
  },
  tituloHistorico: { fontWeight: 'bold', marginBottom: 8, color: '#0f172a' },
  historicoItem: { borderLeftWidth: 2, borderLeftColor: '#0284c7', paddingLeft: 8 },
  dataHistorico: { fontSize: 12, fontWeight: 'bold', color: '#64748b' },
  textoHistorico: { fontSize: 14, color: '#334155' },
  botaoSalvar: {
    backgroundColor: '#059669',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 20,
  },
  textoBotaoSalvar: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
});